"""ブロック図データから Verilog を生成する。

入力は保存データ (形式1・形式2どちらでもよい)、出力は Verilog のソース文字列。
データの読み解きは netlist.py が持つ。ここは出力に専念する。

このモジュールは Qt に依存しない。GUI を起動せずにテストできるように
意図的に分離してある。単体でも使える:

    python verilog.py diagram.json out.v
"""

from __future__ import annotations

import json
import sys

import netlist


class GenerationError(Exception):
    """Verilog を生成できないときに送出する。"""


# --------------------------------------------------------------------------
# 検査
# --------------------------------------------------------------------------

def _validate(design):
    if not design.inputs and not design.outputs and not design.instances:
        raise GenerationError("図が空です。")

    if not design.name:
        raise GenerationError("モジュール名が空です。")

    seen = set()
    for instance in design.instances:
        if not instance.module_name:
            raise GenerationError("モジュール名が空のサブモジュールがあります。")
        if not instance.name:
            raise GenerationError(
                f"'{instance.module_name}' のインスタンス名が空です。")
        if instance.name in seen:
            raise GenerationError(
                f"インスタンス名 '{instance.name}' が重複しています。")
        if design.module_for(instance) is None:
            raise GenerationError(
                f"モジュール '{instance.module_name}' の定義がありません。")
        seen.add(instance.name)


def _collect_wires(design, warnings):
    """宣言が必要な wire を (名前, ビット幅) の順序付きリストで返す。"""
    top_ports = {port.name for port in design.inputs}
    top_ports |= {port.name for port in design.outputs}
    widths, drivers, loads, order = {}, {}, {}, []

    def use(wire, width, where, is_driver):
        if wire not in widths:
            widths[wire] = width
            order.append(wire)
        elif widths[wire] != width:
            warnings.append(
                f"wire '{wire}' のビット幅が一致しません "
                f"({widths[wire]} と {width})。広いほうを採用します")
            widths[wire] = max(widths[wire], width)
        (drivers if is_driver else loads).setdefault(wire, []).append(where)

    # トップから見ると、入力ポートが駆動元・出力ポートが受け側になる
    for port in design.inputs:
        use(port.name, port.width, f"{design.name}.{port.name}", True)
    for port in design.outputs:
        use(port.name, port.width, f"{design.name}.{port.name}", False)

    for instance in design.instances:
        module = design.module_for(instance)
        for direction, port in module.ports():
            wire = instance.wire_for(port.name)
            where = f"{instance.name}.{port.name}"
            if not wire:
                warnings.append(f"{where} が未接続です")
                continue
            use(wire, port.width, where, direction == "output")

    for wire in order:
        wire_drivers = drivers.get(wire, [])
        if not wire_drivers:
            warnings.append(f"wire '{wire}' に駆動元がありません")
        elif len(wire_drivers) > 1:
            warnings.append(
                f"wire '{wire}' が複数から駆動されています: "
                + ", ".join(wire_drivers))
        if not loads.get(wire):
            warnings.append(f"wire '{wire}' がどこにも接続されていません")

    # トップのポート名と同じ wire は、ポート宣言が兼ねるので宣言しない
    return [(wire, widths[wire]) for wire in order if wire not in top_ports]


# --------------------------------------------------------------------------
# 出力
# --------------------------------------------------------------------------

INDENT = "    "


def _bit_range(width):
    return f"[{width - 1}:0]" if width > 1 else ""


def _port_declarations(design):
    entries = [("input", port) for port in design.inputs]
    entries += [("output", port) for port in design.outputs]
    if not entries:
        return []

    range_width = max(len(_bit_range(port.width)) for _, port in entries)
    lines = []
    for direction, port in entries:
        decl = f"{direction:<6} wire"
        if range_width:
            decl += " " + _bit_range(port.width).ljust(range_width)
        lines.append(f"{decl} {port.name}")
    return lines


def _wire_declarations(wires):
    if not wires:
        return []

    range_width = max(len(_bit_range(width)) for _, width in wires)
    lines = []
    for name, width in wires:
        decl = "wire"
        if range_width:
            decl += " " + _bit_range(width).ljust(range_width)
        lines.append(f"{decl} {name};")
    return lines


def _instance_lines(instance, module):
    connections = [(port.name, instance.wire_for(port.name))
                   for _, port in module.ports()]

    lines = [f"{module.name} {instance.name} ("]
    if connections:
        name_width = max(len(name) for name, _ in connections)
        last = len(connections) - 1
        for i, (name, wire) in enumerate(connections):
            comma = "," if i < last else ""
            lines.append(f"{INDENT}.{name.ljust(name_width)} ({wire}){comma}")
    lines.append(");")
    return lines


def _emit(design, wires):
    lines = ["// Generated by blox2rtl.", ""]

    port_lines = _port_declarations(design)
    if port_lines:
        lines.append(f"module {design.name} (")
        last = len(port_lines) - 1
        for i, decl in enumerate(port_lines):
            comma = "," if i < last else ""
            lines.append(f"{INDENT}{decl}{comma}")
        lines.append(");")
    else:
        lines.append(f"module {design.name};")
    lines.append("")

    for decl in _wire_declarations(wires):
        lines.append(f"{INDENT}{decl}")
    if wires:
        lines.append("")

    for instance in design.instances:
        module = design.module_for(instance)
        for line in _instance_lines(instance, module):
            lines.append(f"{INDENT}{line}")
        lines.append("")

    lines.append("endmodule")
    return "\n".join(lines) + "\n"


def generate(data):
    """保存データから (Verilog 文字列, 警告のリスト) を返す。

    構造上 Verilog にできない場合は GenerationError を送出する。
    警告は生成を止めない種類の指摘 (未接続、駆動元なし、ビット幅不一致など)。
    """
    design, warnings = netlist.load(data)
    _validate(design)
    warnings = list(warnings)
    wires = _collect_wires(design, warnings)
    return _emit(design, wires), warnings


# --------------------------------------------------------------------------
# コマンドライン
# --------------------------------------------------------------------------

def main(argv):
    if len(argv) < 2:
        print("usage: python verilog.py <diagram.json> [out.v]", file=sys.stderr)
        return 2

    with open(argv[1], encoding="utf-8") as handle:
        data = json.load(handle)

    try:
        text, warnings = generate(data)
    except GenerationError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)

    if len(argv) > 2:
        with open(argv[2], "w", encoding="utf-8") as handle:
            handle.write(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
