"""verilog.py の回帰テスト。

GUI を起動せずに回せる。標準ライブラリのみ:

    python -m unittest discover -s tests
"""

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import netlist  # noqa: E402
import verilog  # noqa: E402


def module_name(text):
    return {"type": "module_name", "text": text, "x": 0, "y": 0}


def port(name, width=1, is_input=True, y=0):
    return {
        "type": "port",
        "name": name,
        "width": width,
        "is_input": is_input,
        "x": 0,
        "y": y,
    }


def submodule(module, instance, inputs=(), outputs=(), x=0, y=0):
    return {
        "type": "submodule",
        "x": x,
        "y": y,
        "module_data": {
            "module_name": module,
            "instance_name": instance,
            "inputs": [list(entry) for entry in inputs],
            "outputs": [list(entry) for entry in outputs],
        },
    }


class GenerateTest(unittest.TestCase):
    def test_full_module(self):
        diagram = [
            module_name("counter"),
            port("din", 8, is_input=True),
            port("dout", 1, is_input=False),
            submodule(
                "adder", "u_add",
                inputs=[("a", 8, "din"), ("b", 4, "mid")],
                outputs=[("y", 1, "dout")],
                x=100,
            ),
            submodule("gen", "u_gen", outputs=[("q", 4, "mid")], x=50),
        ]

        text, warnings = verilog.generate(diagram)

        self.assertEqual(warnings, [])
        self.assertEqual(text, (
            "// Generated by blox2rtl.\n"
            "\n"
            "module counter (\n"
            "    input  wire [7:0] din,\n"
            "    output wire       dout\n"
            ");\n"
            "\n"
            "    wire [3:0] mid;\n"
            "\n"
            "    gen u_gen (\n"
            "        .q (mid)\n"
            "    );\n"
            "\n"
            "    adder u_add (\n"
            "        .a (din),\n"
            "        .b (mid),\n"
            "        .y (dout)\n"
            "    );\n"
            "\n"
            "endmodule\n"
        ))

    def test_top_port_is_not_redeclared_as_wire(self):
        """トップのポート名と同じ wire は宣言しない (ポート宣言が兼ねる)。"""
        diagram = [
            module_name("top"),
            port("clk", 1, is_input=True),
            submodule("ff", "u_ff", inputs=[("clk", 1, "clk")], x=0),
        ]
        text, _ = verilog.generate(diagram)
        self.assertNotIn("wire clk;", text)
        self.assertIn(".clk (clk)", text)

    def test_ports_follow_vertical_position(self):
        """JSON 内の順序ではなく、図の上から下の順に並べる。"""
        diagram = [
            module_name("top"),
            port("c", 1, is_input=True, y=200),
            port("a", 1, is_input=True, y=0),
            port("b", 1, is_input=True, y=100),
        ]
        design, _ = netlist.load(diagram)
        self.assertEqual([p.name for p in design.inputs], ["a", "b", "c"])

    def test_instances_follow_signal_flow(self):
        """インスタンスは左から右 (信号の流れ) の順に出す。"""
        diagram = [
            module_name("top"),
            submodule("c", "u_c", x=300),
            submodule("a", "u_a", x=0),
            submodule("b", "u_b", x=150),
        ]
        design, _ = netlist.load(diagram)
        self.assertEqual(
            [i.name for i in design.instances], ["u_a", "u_b", "u_c"]
        )

    def test_port_entry_without_wire_name(self):
        """SubmoduleDialog は Wire 名が空だと 2 要素で返す。未接続として扱う。"""
        diagram = [
            module_name("top"),
            submodule("blk", "u_blk", inputs=[("a", 1)], outputs=[("y", 1, "out")]),
        ]
        text, warnings = verilog.generate(diagram)
        self.assertIn(".a ()", text)
        self.assertIn("u_blk.a が未接続です", warnings)


class WarningTest(unittest.TestCase):
    def generate_warnings(self, diagram):
        return verilog.generate(diagram)[1]

    def test_multiple_drivers(self):
        diagram = [
            module_name("top"),
            submodule("a", "u_a", outputs=[("y", 1, "net")], x=0),
            submodule("b", "u_b", outputs=[("y", 1, "net")], x=10),
            submodule("c", "u_c", inputs=[("d", 1, "net")], x=20),
        ]
        warnings = self.generate_warnings(diagram)
        self.assertTrue(
            any("複数から駆動" in w and "net" in w for w in warnings), warnings
        )

    def test_undriven_wire(self):
        diagram = [
            module_name("top"),
            submodule("a", "u_a", inputs=[("d", 1, "net")]),
        ]
        warnings = self.generate_warnings(diagram)
        self.assertIn("wire 'net' に駆動元がありません", warnings)

    def test_width_mismatch(self):
        diagram = [
            module_name("top"),
            submodule("a", "u_a", outputs=[("y", 8, "net")], x=0),
            submodule("b", "u_b", inputs=[("d", 4, "net")], x=10),
        ]
        text, warnings = verilog.generate(diagram)
        self.assertTrue(any("ビット幅が一致しません" in w for w in warnings), warnings)
        # 広いほうを採用する
        self.assertIn("wire [7:0] net;", text)


class ErrorTest(unittest.TestCase):
    def test_empty_diagram(self):
        with self.assertRaises(verilog.GenerationError):
            verilog.generate([module_name("top")])

    def test_duplicate_instance_name(self):
        diagram = [
            module_name("top"),
            submodule("a", "u_dup", x=0),
            submodule("b", "u_dup", x=10),
        ]
        with self.assertRaises(verilog.GenerationError) as caught:
            verilog.generate(diagram)
        self.assertIn("u_dup", str(caught.exception))

    def test_empty_module_name(self):
        diagram = [module_name("top"), submodule("", "u_a")]
        with self.assertRaises(verilog.GenerationError):
            verilog.generate(diagram)


if __name__ == "__main__":
    unittest.main()
